### ISSUE TITLE
the preformace of RefineGan

### ISSUE THREAD

**Issue by Liujingxiu23** [Kahsolt/TransTacoS-RetuneGAN#1]
Hi thank you very much for your work and sharing!

I am interested on the preformance of RefineGan.
The demo wavesamples in https://timedomain-tech.github.io/refinegan/ are great.
Have you tried the original version of RefineGan and  could you get the similar results?
What is compared with hifigan in singing voice synthesis?

**Comment by Kahsolt** [comment]
Thank for your attention!

1. I could NOT get the original version of RefineGAN. Because it would probably not be made open-source, as I asked one of the the authors months ago.
2. Wavesamples on their demo page sounds really amazing, but according to my experiments and understanding, what matters is NOT that proposed U-Net model architeture or the artifacted wavform template, but the training on: 
  - studio-grade quality recordings with higher sampling rate (44.1kHz ranther than 16kHz/22.05kHz)
  - larger dataset (~60 hours)
  - more accurate input melspec (128 bands rather than 80 bands in MelGAN)
  - more model parameters (reaches hidden_dim=512 in the bottleneck of the U-Net)
3. Compared with HiFiGAN in TTS task, we usually expect higher dynamic and pitch response in SVS task, thus RefineGAN indeed made two improvements:
  - applies data augmentation: pitch-shift and loudness-adjust helps better modeling (on naive trained HiFiGAN, when you change input melspec's magnitude, it will probably generate glitches or constant noises with high frequncy, rather than the expected behaviour: accordingly change audio volume)
  - introduces waveform template as an auxiliar input: on a higher level of understanding, it works as the author's claim: "let the model render a rough template"; but at lower level, it's a sense of condition: "we condition a piece of melspec on given waveform segment"

**Comment by Kahsolt** [comment]
To get an applicable GAN-based vocoder, I recommend jaywalnut310's MelGAN-Pytorch (https://github.com/jaywalnut310/MelGAN-Pytorch). It converges very slow, but feed it with clean data and take patience ~
Here is the balance:
- GAN loss on time domain converges slow, but will finally leads to very clear human-like consonants
- acoustic loss on spectrum domain (mel_loss, mstft_loss, etc.) converges fast, but it models vowels well while ruins consonants

**Comment by Liujingxiu23** [comment]
Thank you for your reply.
I am actually interested in the part of  "speech template", it seems looks like NSF model(source-filter-based waveform model) which also use sinc waveform.  The vocoder I used now is hifigan, RefineGan seems has similar model structure as  hifigan. And what I want to do is to add "sinc waveform form based on pitch" to my hifigan model to update the performance.
Especially the performance  in "long vowel synthesis" in singing voice synthesis.  Now, there are glitches in wavesample generated。But I checked the predicted f0, the values seems good.
So I am wondering if "sinc wave form based on pitch" will be helpfull? Do you have any experience? 
![image](https://user-images.githubusercontent.com/49260794/183611137-9c3d0c71-fb93-433a-8f5d-8ebc91a5dbd9.png)

**Comment by Kahsolt** [comment]
Bingo! According to the author, RefineGAN is right developed basing on HiFiGAN. 
I'm interested in this "sinc waveform form based on pitch" and "seeming good predicted f0".

1. I guess you mean that, you wanna modify hifigan to produce several sinc wavelets (e.g. 80 signals of different frequences), then mix them up to generated the final signal? 
This sounds a formant vocoder back in the 1980s and I have once thought about it, naming it WaveletGAN, which may be a good idea but I didn't have time to implement it. 
The CNN might be capable to predict 80 pure wavelets, but how to mix them up while avoiding phase confliction is still a hard task for a CNN. 
Another risk of this method is that, only allowing a NN to predict coeficient of sinc wavelets might somewhat limit model output diversity, I don't know if this will be ok.
2. I wonder whether your f0 is synchronously predicted by your modified HiFiGAN, or obtained by DSP process on the generated waveform. 
F0 contour estmation is usally smoothed by algorimthms, so that it "seems good".
3. For long vowel glitches, solutions I know: HiFiGAN trains on waveform segments with fixed length rather that a whole recording; UnivNet(?) introduces a multi-length discriminator working on short/medium/long audio clips separatly.
Another trick might be useful is that, carefully design your convolution layers with `padding='valid'`, because zero padding leaks the boundary information as reported in some CV essays.

Might these be helpful :)

**Comment by Liujingxiu23** [comment]
hi thank you for your reply!
1. I did not mean "wavlets", I just mean “speech template” which is sinusoidal wave samples generated based on pitch。I have not had any idea about wavelet. I am only familiar with pure NN mothod like hifigan that with no signal processing knowledge related.
2. My subjest is Singing voce synthesis which includes acoustic model and vocoder model. Acoustic Model train and predict f0 and mels. In inference,  even though the predicted f0 seems right, the generated waves also has glitches . I did not figure out the reason.
3. Good idea, I did not aware this kind of problem, I will try to see whether "multi-length" and "pad" will help.
